#!/usr/bin/env bash
# Regenerates DOC.md from the current tree. Lightweight module map, not full rustdoc.
set -euo pipefail
cd "$(dirname "$0")/.."

out=DOC.md

{
  echo "# Plaste — Project Overview"
  echo
  echo "_Auto-generated by \`scripts/generate_docs.sh\`. Do not edit by hand._"
  echo
  echo "## Backend modules (\`src/\`)"
  echo
  for f in src/*.rs; do
    name=$(basename "$f")
    # first //! or // doc/comment line as one-line purpose, else "(no doc comment)"
    purpose=$(grep -m1 -E '^\s*//!?' "$f" | sed -E 's/^\s*\/\/!?\s?//' || true)
    [ -z "$purpose" ] && purpose="(no doc comment)"
    echo "- **$name** — $purpose"
  done
  echo
  echo "## HTTP endpoints"
  echo
  grep -hoE '\.route\(\s*"[^"]+"' src/*.rs | sed -E 's/^\.route\(\s*"//; s/"$//' | sort -u | while read -r path; do
    echo "- \`$path\`"
  done
  echo
  echo "## Frontends"
  echo
  for d in client admin-dashboard file-explorer; do
    [ -d "$d" ] || continue
    echo "- **$d/** — $( [ -f "$d/package.json" ] && grep -m1 '"name"' "$d/package.json" | sed -E 's/.*"name":\s*"([^"]+)".*/\1/' || echo "$d" )"
  done
} > "$out"

echo "Wrote $out"
